### ISSUE TITLE
Make savegames persistent in web browser

### ISSUE THREAD

**Issue by intgr** [intgr/uqm-wasm#4]
It's clearly unreasonable to expect anyone to hold their browser process alive for the whole playthrough of the game. :)

Figure out if localStorage or some other system is appropriate for persisting the files.

**Comment by NotAYakk** [comment]
LocalStorage is medium-persistant, but can be cleared accidentally.  It is a good first step.  And you can turn it on relatively easily.

For a next step, add an external button that lets you backup the localStorage save games to a file (and replace it).

**Comment by noamr** [comment]
I had a couple of days off and wanted to play UQM on my browser
so I fixed this using IDBFS: https://github.com/noamr/uqm-wasm
The thing is that it requires a newer version of EMSDK because of the pesky libpng bug. For now I workaround that by compiling own version of libpng, I'm not sure if that's the right approach or if it's upstreamable.

**Comment by noamr** [comment]
OK made the libpng thing better, see https://github.com/intgr/uqm-wasm/pull/7
